database:
    restart: always
    image: postgres:latest
    volumes:
        - pgdata:/var/lib/postgresql/data/
restapi:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - /usr/src/app
    ports:
        - "8000:8000"
    links:
        - database
    environment:
        DEBUG: "true"
